"""Repository pattern for the operations + research-lab data model.

The ``Store`` protocol defines the persistence surface every consumer
(``OpsService``, voice-first agent, blockchain attester, recall trace) talks
to. ``InMemoryStore`` is the default; it satisfies the protocol against a
plain dict and is what tests and local development use. A future
``PostgresStore`` (Workstream 2 follow-up) implements the same protocol
against migration 009's tables once it lands in Neon.

Design notes:

* The store is intentionally CRUD-shaped, not query-shaped. Business rules
  (stage transitions, lot grading, recall traversal) live in
  ``service.py``; the store is dumb persistence.
* Identifiers are UUIDs generated by Pydantic models, NOT by the store. This
  keeps the InMemoryStore deterministic in tests and avoids a round-trip
  to fetch the autogenerated id on insert.
* Event tables (``TrackingEvent``, ``HACCPCheck``, ``EnvironmentalReading``,
  ``ContaminationEvent``, ``SOPExecution``) are append-only. The store
  exposes ``add_*`` for these, never ``update_*``.
* Reads return None on miss, not raise. Service-layer code decides whether
  a miss is an error.
"""

from __future__ import annotations

from typing import Iterable, Protocol
from uuid import UUID

from crowe_synapse_engine.ops.models import (
    Batch,
    ContaminationEvent,
    EnvironmentalReading,
    HACCPCheck,
    Lot,
    SOPExecution,
    Strain,
    TrackingEvent,
)


class Store(Protocol):
    """Persistence contract for the ops layer.

    Implementations must be process-safe but not necessarily thread-safe;
    callers wrap concurrent access at the service layer.
    """

    # Mutable rows -------------------------------------------------------

    def get_batch(self, batch_id: UUID) -> Batch | None: ...
    def get_batch_by_code(self, code: str) -> Batch | None: ...
    def list_batches(self, *, archived: bool = False) -> list[Batch]: ...
    def save_batch(self, batch: Batch) -> Batch: ...

    def get_lot(self, lot_id: UUID) -> Lot | None: ...
    def get_lot_by_code(self, code: str) -> Lot | None: ...
    def lots_for_batch(self, batch_id: UUID) -> list[Lot]: ...
    def save_lot(self, lot: Lot) -> Lot: ...

    def get_strain(self, strain_id: UUID) -> Strain | None: ...
    def save_strain(self, strain: Strain) -> Strain: ...

    # Append-only event rows ---------------------------------------------

    def add_tracking_event(self, event: TrackingEvent) -> TrackingEvent: ...
    def tracking_events_for_batch(self, batch_id: UUID) -> list[TrackingEvent]: ...
    def tracking_events_for_lot(self, lot_id: UUID) -> list[TrackingEvent]: ...

    def add_haccp_check(self, check: HACCPCheck) -> HACCPCheck: ...
    def haccp_checks_for_batch(self, batch_id: UUID) -> list[HACCPCheck]: ...

    def add_environmental_reading(
        self, reading: EnvironmentalReading
    ) -> EnvironmentalReading: ...
    def environmental_readings_for_batch(
        self, batch_id: UUID
    ) -> list[EnvironmentalReading]: ...

    def add_contamination_event(
        self, event: ContaminationEvent
    ) -> ContaminationEvent: ...
    def contamination_events_for_batch(
        self, batch_id: UUID
    ) -> list[ContaminationEvent]: ...

    def add_sop_execution(self, execution: SOPExecution) -> SOPExecution: ...


class InMemoryStore:
    """Reference implementation of ``Store`` backed by Python dicts.

    Suitable for tests, local development, and demo runs. Lifetime is the
    process; nothing persists across restarts. Safe to construct fresh in
    every test via a pytest fixture.
    """

    def __init__(self) -> None:
        self._batches: dict[UUID, Batch] = {}
        self._lots: dict[UUID, Lot] = {}
        self._strains: dict[UUID, Strain] = {}
        self._tracking_events: list[TrackingEvent] = []
        self._haccp_checks: list[HACCPCheck] = []
        self._environmental: list[EnvironmentalReading] = []
        self._contamination: list[ContaminationEvent] = []
        self._sop_executions: list[SOPExecution] = []

    # Batches ------------------------------------------------------------

    def get_batch(self, batch_id: UUID) -> Batch | None:
        return self._batches.get(batch_id)

    def get_batch_by_code(self, code: str) -> Batch | None:
        return next((b for b in self._batches.values() if b.code == code), None)

    def list_batches(self, *, archived: bool = False) -> list[Batch]:
        return [
            b for b in self._batches.values() if (b.archived_at is not None) == archived
        ]

    def save_batch(self, batch: Batch) -> Batch:
        self._batches[batch.id] = batch
        return batch

    # Lots ---------------------------------------------------------------

    def get_lot(self, lot_id: UUID) -> Lot | None:
        return self._lots.get(lot_id)

    def get_lot_by_code(self, code: str) -> Lot | None:
        return next((lot for lot in self._lots.values() if lot.code == code), None)

    def lots_for_batch(self, batch_id: UUID) -> list[Lot]:
        return [lot for lot in self._lots.values() if lot.batch_id == batch_id]

    def save_lot(self, lot: Lot) -> Lot:
        self._lots[lot.id] = lot
        return lot

    # Strains ------------------------------------------------------------

    def get_strain(self, strain_id: UUID) -> Strain | None:
        return self._strains.get(strain_id)

    def save_strain(self, strain: Strain) -> Strain:
        self._strains[strain.id] = strain
        return strain

    # Append-only events -------------------------------------------------

    def add_tracking_event(self, event: TrackingEvent) -> TrackingEvent:
        self._tracking_events.append(event)
        return event

    def tracking_events_for_batch(self, batch_id: UUID) -> list[TrackingEvent]:
        return [e for e in self._tracking_events if e.batch_id == batch_id]

    def tracking_events_for_lot(self, lot_id: UUID) -> list[TrackingEvent]:
        return [e for e in self._tracking_events if e.lot_id == lot_id]

    def add_haccp_check(self, check: HACCPCheck) -> HACCPCheck:
        self._haccp_checks.append(check)
        return check

    def haccp_checks_for_batch(self, batch_id: UUID) -> list[HACCPCheck]:
        return [c for c in self._haccp_checks if c.batch_id == batch_id]

    def add_environmental_reading(
        self, reading: EnvironmentalReading
    ) -> EnvironmentalReading:
        self._environmental.append(reading)
        return reading

    def environmental_readings_for_batch(
        self, batch_id: UUID
    ) -> list[EnvironmentalReading]:
        return [r for r in self._environmental if r.batch_id == batch_id]

    def add_contamination_event(self, event: ContaminationEvent) -> ContaminationEvent:
        self._contamination.append(event)
        return event

    def contamination_events_for_batch(
        self, batch_id: UUID
    ) -> list[ContaminationEvent]:
        return [e for e in self._contamination if e.batch_id == batch_id]

    def add_sop_execution(self, execution: SOPExecution) -> SOPExecution:
        self._sop_executions.append(execution)
        return execution

    # Introspection helpers (test-only) ----------------------------------

    def _all_tracking_events(self) -> list[TrackingEvent]:
        return list(self._tracking_events)

    def _all_contamination_events(self) -> list[ContaminationEvent]:
        return list(self._contamination)


def get_default_store() -> Store:
    """Return the configured default store.

    Reads ``CROWE_OPS_STORE`` env var. Defaults to InMemoryStore. When the
    Postgres adapter ships (Workstream 2 Phase 2), this is the seam where
    ``CROWE_OPS_STORE=postgres`` will route to it.
    """
    import os

    backend = os.environ.get("CROWE_OPS_STORE", "memory").lower()
    if backend == "memory":
        return InMemoryStore()
    raise NotImplementedError(
        f"Store backend {backend!r} is not yet implemented. "
        f"Set CROWE_OPS_STORE=memory or implement a new adapter."
    )


def iter_recall_forward(store: Store, batch_id: UUID) -> Iterable[TrackingEvent]:
    """Yield every tracking event reachable forward from a batch.

    Used for FSMA 204 recall queries: given a contaminated batch, which
    lots and downstream events were derived from it? Walks the batch ->
    lots -> tracking_events graph in insertion order, deduplicating events
    that match both the batch and one of its lots (harvest and ship events
    carry both ids).
    """
    seen: set[UUID] = set()
    for event in store.tracking_events_for_batch(batch_id):
        if event.id not in seen:
            seen.add(event.id)
            yield event
    for lot in store.lots_for_batch(batch_id):
        for event in store.tracking_events_for_lot(lot.id):
            if event.id not in seen:
                seen.add(event.id)
                yield event
